/**
 * @binblink/plugin-sdk-mobile
 *
 * BedCode 移动端插件开发工具包
 */

export type {
  Disposable,
  PluginType,
  PluginState,
  PluginManifest,
  PluginConfiguration,
  ConfigProperty,
  MobilePluginContributes,
  LifecycleContribution,
  CommandContribution,
  ViewContribution,
  NavTabContribution,
  SettingsContribution,
  RouteContribution,
  TerminalContribution,
  TerminalToolbarItemContribution,
  ToolboxPageDescriptor,
  NavTabDescriptor,
  TerminalToolbarItemDescriptor,
  SettingsSectionDescriptor,
  PluginRouteDescriptor,
  CommandRegistry,
  TerminalAPI,
  SessionAPI,
  UIRegistry,
  EventAPI,
  StorageAPI,
  I18nAPI,
  LifecycleAPI,
  LoggerAPI,
  DialogOptions,
  DialogResult,
  DialogAPI,
  NotificationAPI,
  StatusAPI,
  UploadRequestMeta,
  UploadHookDecision,
  TransferRequestMeta,
  MountOptions,
  FileServiceMount,
  PeerMountAnnouncement,
  PeerFileServiceInfo,
  FileServiceAPI,
  SystemAPI,
  SafAPI,
  SafEntry,
  SafCopyHandle,
  SafCopyStatus,
  PickedSharedDirectory,
  PluginDevMock,
  PluginContext,
  PluginModule,
  MobileHttpResult,
  MobileQueueTaskItem,
  MobileHostApi,
} from './types'

export {
  getSharedModule,
  getI18n,
  getVue,
  getVueI18n,
  getPinia,
  getRouter,
  getPluginContext,
  getPresetTasks,
  getMobileApi,
} from './runtime'
