[package]
name = "bedcode_plugin_ai_chatbox"
version = "1.0.0-beta"
description = "AI Chatbox Plugin (Mobile)"
authors = ["BedCode"]
edition = "2021"

[features]
default = []
wasm = []

[lib]
crate-type = ["cdylib"]

[dependencies]
bedcode-plugin-api-mobile = { path = "../../../packages/plugin-sdk-mobile/rust", features = ["wasm"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
